### ISSUE TITLE
Cell voltages not shown for cells 7 and 8

### ISSUE THREAD

**Issue by ryba-xek** [stawel/cheali-charger#102]
I've flashed v 1.0 firmware into my Accucell-8 yesterday, calibrated e t. c.
Works great, thanks, however I can't make it display cell voltages for cells 7 and 8.
See video.
It seems like the software tries to show the screen, but fails, so cell voltages 4,5,6 remain.

http://www.youtube.com/watch?v=ooQTplB-h9A

**Comment by ryba-xek** [comment]
Same for 7-cell battery.

**Comment by stawel** [comment]
bug fixed

Best Regards,
Paweł

**Comment by ryba-xek** [comment]
Thanks a lot. Really a great project.
