### ISSUE TITLE
FAN controller

### ISSUE THREAD

**Issue by GGyuri** [stawel/cheali-charger#113]
Hi Pawel

The fan control problem for all versions.

I setting in menu FAN ON 50C
IN TEMP:44,7-44,8  and fan on-off, on-off, on-off....... 
(no hysteresis)

Please chek it
Thanks
Gyuri

**Comment by stawel** [comment]
Thanks Gyuri for the ticket, unfortunately this bug is hard to fix
that's why I didn't fix it yet, but I will work on it this weekend

I do have a question: Is the temperature value stable over time?
(the value changes not more then ~0.5C?)

**Comment by stawel** [comment]
ok, should be fixed now

Best Regards
Paweł
