### ISSUE TITLE
If cheali-charger support IMAX B6 mini?

### ISSUE THREAD

**Issue by 3835** [stawel/cheali-charger#149]
Hi! 
First question is in the topic, and second question, how cooperation cheali-charger with LogView Studio? I ask because, now my charger "not talking" with this software, and i really think about new firmware:)

**Comment by stawel** [comment]
1. no, we don't support Imax B6 mini yet
2. yes, we do support LogView (and LogView Studio)

**Comment by 3835** [comment]
#stawel thanks for quick answer and I keep my fingers crossed for cheali-charger development!

**Comment by Milek7** [comment]
For dumping data from this charger, you can use my script: https://github.com/Milek7/imax-b6mini-datalogger/blob/master/imax-b6mini-datalogger.py
I don't know LogView, but if it supports .csv files it should work.

**Comment by ireun** [comment]
@stawel  is it still not supported?

**Comment by ireun** [comment]
Yup, You've explained that here: https://github.com/stawel/cheali-charger/issues/106#issuecomment-222520952 in ticket #106. Dziękuję mimo wszystko. ;)

**Comment by stawel** [comment]
to ja dziękuję za commita :) i pozdrawiam
