### ISSUE TITLE
Generate images for documenation

### ISSUE THREAD

**Issue by burunduk** [stawel/cheali-charger#153]
Have refresh images to documents.
The archive contains the font and script to generate images
Script use ImageMagick for generate images from xpm fonts.

[xpm.zip](https://github.com/stawel/cheali-charger/files/184553/xpm.zip)
![example](https://cloud.githubusercontent.com/assets/912818/13959894/9e433670-f05e-11e5-881f-6d101b761c9f.png)

**Comment by stawel** [comment]
wow!
can I add your script and fonts to the projects repository?

**Comment by burunduk** [comment]
Yes, please.

**Comment by stawel** [comment]
generator added to:
https://github.com/stawel/cheali-charger/tree/master/utils/lcdScreenshotGenerator

settings documentation looks much better now :)
https://github.com/stawel/cheali-charger/blob/master/docs/settings/settings.md

Thank you very much!
