### ISSUE TITLE
settings: add reverse menu "up" "down" buttons

### ISSUE THREAD

**Issue by stawel** [stawel/cheali-charger#159]

**Comment by darkcheater** [comment]
this would be a cool feature so you can go down with the < arrow left button and up with the arrow right > button. In my particular charger, there are "real" up/down buttons so it would just be better to have it this way. Please let me know your opinion.
![20160407_233126](https://cloud.githubusercontent.com/assets/15660491/14367731/ffdccb72-fd19-11e5-9dc5-a607a64f3361.jpg)
