### ISSUE TITLE
hex and eep files

### ISSUE THREAD

**Issue by dankohs** [stawel/cheali-charger#171]
Please help. 
I can't find .hex or .eep files for eco8 charger. I am using eXtreme burner. How to download files needed to flash the charger?

Thanks

**Comment by stawel** [comment]
if you have a atmega32 CPU then:
https://github.com/stawel/cheali-charger/blob/master/hex/unstable/cheali-charger-HobbyKing-ECO8-150W-7A-8S_1.99-20160419_atmega32.hex
(press the "RAW" button)

**Comment by dankohs** [comment]
Thank you. But, i want to flash it so i can calibrate balance port on it, to unlock service menu1; i think that is called. For that i would need modified eeprom file? Chip is atmega32A.

**Comment by stawel** [comment]
you mean the original firmware?
I don't know where you can find it, sorry,
but you should also ask on the cheali-charger@googlegroups.com mailing list.
