### ISSUE TITLE
Default discharge voltage LiFePO4 2.0v too low - proposal 2.5v

### ISSUE THREAD

**Issue by PascalRZ** [stawel/cheali-charger#184]
Hi Pawel, hi all,

Using Cheali Charger, I found that the default discharge voltage value for LiFePO4 batteries is 2.0v/element

This value is too low and can damage the battery. I learned LiFePO4 during an electric bike project consisting of a NiMH to LiFePO4 conversion.

A few years ago, manufacturers wrote that 2.0v was the minimum discharge voltage. Now, some manufacturers write the minimum discharge voltage is 2.5v and BMS (battery monitor system) has to deactivate everything before falling to 2.0v

Because some manufacturers continue to declare 2.0v but some of them declare 2.5v, I recommend to change the default value to 2.5v
If somebody wants to go down to 2.0v, he will change the value using the advanced parameters (a default value must be safe and a beginner will not use the advanced parameters).

Sources:

http://www.pdbattery.com/prismatic-lifepo4-battery.html 

http://www.heterbattery.com/products/lithium-ion-cells/lifepo4-battery-18650-1400mah

http://en.calb.cn/product/show/?id-630

http://www.evpst.com/Product.asp?bid=17&BigClassName=LiFePo4%20battery

In my bike:

http://www.aliexpress.com/item/New-Lifepo4-battery-cell-10ah-3-2V-3C-discharge-electric-scooter-battery-packs-for-bicycle-electric/32330083547.html

http://www.ebay.fr/itm/24V-25-6V-30A-LiFePo4-Battery-BMS-LFP-PCM-SMT-System-8S-3-2V-eBike-Battery-8x-3V-/321732147949?hash=item4ae8bafaed

What do you think about this proposal?
Pascal

**Comment by stawel** [comment]
The 2.0V is based on the imaxB6 manual http://www.ittgroup.ee/files/IMAX_B6_manual.pdf
but since increasing the the cutoff voltage should be safer for the user, it's probably a good idea.

I will change it to 2.5V as soon as possible
