### ISSUE TITLE
Current calibration bug causes HW failure when charging

### ISSUE THREAD

**Issue by bikemike** [stawel/cheali-charger#187]
I just installed cheali-charger-imaxB6-clone_2.00-e10.3.12-20160613_nuvoton-M051 and I was having an issue trying to charge my lipos.

I calibrated the current and voltage properly but kept getting the following error message between 13 and 34 seconds into the charge procedure.

error: HW failure

When I went back into the 1amp current calibration I noticed that the calculated value was much higher than what the meter was reading so I redid the calibration again. I exited and went back in several times and it seemed as though the calibration kept forgetting what it should be.

Eventually I somehow got it to stick and now my battery has been charging for 7 minutes.

**Comment by stawel** [comment]
if you have any problems during calibration, you should:
1. reset eeprom to default: "options"->"reset default"
2. do the calibration again 
 - first voltage calibration
 - the current calibration

I'm guessing you had one of the calibration points set wrong (probably the 100mA), and 
you've changed the second one.
