### ISSUE TITLE
Accucell 6 50w with Megawin. Any code?

### ISSUE THREAD

**Issue by Isaac96** [stawel/cheali-charger#189]
Is there any code for the Accucell 6 50W 6 amp charger? My one has a Megawin CPU and USB port.
It works with Chargemaster.

**Comment by Isaac96** [comment]
Sorry, saw https://github.com/stawel/cheali-charger/issues/106

**Comment by Isaac96** [comment]
Is there an alternate firmware?

**Comment by stawel** [comment]
I'm not aware of any, sorry.
