### ISSUE TITLE
Unable to build, narrowing uint16_t to int16_t

### ISSUE THREAD

**Issue by diggit** [stawel/cheali-charger#195]
Hi,
I am trying to build upstream version. Running on arch, GCC 6.1.1 throws error
```
cheali-charger/src/core/menus/ProgramDataMenu.cpp:124:1:` error: narrowing conversion of '65516u' from 'AnalogInputs::ValueType {aka unsigned int}' to 'int16_t {aka int}' inside { } [-Wnarrowing]
 };
 ^
```

**Comment by stawel** [comment]
hm... this bug if already fixed in the "develop" branch, unfortunately it will take some time until 
I can merge these two branches.

**Comment by diggit** [comment]
Ok, but it is common to have working version in default (mostly master) branch. It doesn't matter for me, so of nobody else complains, forget it...
