### ISSUE TITLE
Two versions of Turnigy Accucell 6

### ISSUE THREAD

**Issue by list1999** [stawel/cheali-charger#219]
Here is a review of two versions of Turnigy Accucell 6 (www.microtforum.com/viewtopic.php?f=25&t=21751), I have the first version, completely similar to the imaxB6 original. What kind of firmware should I choose - cheali-charger-imaxB6-original_2.01-e10.3.12-20170311_atmega32.hex or cheali-charger-Turnigy-Accucel-6-50W-6A_2.01-e10.3.12-20170311_atmega32.hex?

**Comment by diggit** [comment]
Hi,
**cheali-charger-Turnigy-Accucel-6-50W-6A** is the right one. AFAIK version 2 has not compatible MCU with cheali-charger FW.

**Comment by fiveangle** [comment]
There are multiple versions of the Turnigy 6A.  If the board inside is labelled "SK6000A 10/10/2009" "PCB 6A" then the Turnigy hex above will not work and the imaxB6 hex you stated above will work, but will only get you 5A.  I have this board and have compiled for 6A (hex attached):

[imaxB6-original_6A_atmega32.hex.txt](https://github.com/stawel/cheali-charger/files/962330/imaxB6-original_6A_atmega32.hex.txt)

**Comment by list1999** [comment]
I have this board (https://yadi.sk/i/IVz7PwWq3HTn3V), my only modification is to solder the connector for firmware. Recorded the firmware cheali-charger-Turnigy-Accucel-6-50W-6A_2.01-e10.3.12-20170311_atmega32.hex. Calibration was done with the aid of a device Hold Peak HP890CN. Calibration is saved, Charging is working.

**Comment by fiveangle** [comment]
That's the board. Good to hear the release 6A FW works. I don't know why calibration couldn't complete with the one I have. But haven't tried 2.01 so may check it out at some point (but charger working perfectly with the ImaxB6 target with max current increased to 6A.

**Comment by diggit** [comment]
@fiveangle If it fails, post error code, so we can locate problem.
