### ISSUE TITLE
Do PB settings suite AGM batteries?

### ISSUE THREAD

**Issue by hryamzik** [stawel/cheali-charger#282]
I've replaced my PB battery with an AGM one and was warned that regular PB charges can damage it.

I have to say that sounds ridicules as these batteries are supposed to suite regular cars with the same charging parameters as PB batteries had.

The only limits I managed to find are max voltage of 14.4 V and max current 10% of capacity.

**Comment by diggit** [comment]
That should be it. 2.4V per cell should prevent gassing which AGMs don't like. Also setting reasonable charging current is good idea.

**Comment by hryamzik** [comment]
Thanks, that's exactly what I've done (2,4V, 5A for 60A/H). I've seen voltage temporary getting higher than 14.4 on the last seconds of charging, hope it's not that bad.
