### ISSUE TITLE
i have imax b6 clone pcb "2017.06.09 b680W v1.0"

### ISSUE THREAD

**Issue by radioman666** [stawel/cheali-charger#283]
i have imax b6 clone pcb "2017.06.09 b680W v1.0" on atmega 32a with note additional op-amp
the board is similar to imaxB6-50W-BOA6-nuvoton-M0517
I used different for atmega32, but does not work correctly voltage.

what firmware should i use?

**Comment by radioman666** [comment]
https://github.com/stawel/cheali-charger/issues/277
same problem
I will try today

**Comment by diggit** [comment]
B6AC should do the job. How did it go?

**Comment by radioman666** [comment]
have not tried it yet

**Comment by radioman666** [comment]
first reselt on dual b6ac HEX:
very good calibration
i connected "BAL0" and Y0 HEF4051, but was not connected - accurately measures resistance wires.
