### ISSUE TITLE
MonsterTronic MT680AC

### ISSUE THREAD

**Issue by sharkyenergy** [stawel/cheali-charger#292]
Hello! 

is this charger supported? it has an atmega chip, and the layout looks very similar to the original B6, but is not identical. The original software is full of bugs..

https://monstertronic.org/details/E-04

thank you!

**Comment by TBAMax** [comment]
Hello
Can you share pictures of the board?

**Comment by sharkyenergy** [comment]
sure! here we go:

![photo_2020-05-27_17-21-46](https://user-images.githubusercontent.com/24428068/83039661-ba2ab900-a03e-11ea-9e25-be280aa85f2b.jpg)
![photo_2020-05-27_17-21-51](https://user-images.githubusercontent.com/24428068/83039666-bb5be600-a03e-11ea-8687-b105f5fd3037.jpg)
![photo_2020-05-27_17-21-56](https://user-images.githubusercontent.com/24428068/83039668-bb5be600-a03e-11ea-9e4e-ce5d40105128.jpg)
![photo_2020-05-27_17-22-00](https://user-images.githubusercontent.com/24428068/83039670-bbf47c80-a03e-11ea-882f-4bb38047f67a.jpg)

**Comment by diggit** [comment]
At first glance, pinout seems same as other chargers. This one features additional OpAmp for proper measurement of bottom 2 cells (common for 80W charger variants). I'd try `cheali-charger-Dual-Power-B6AC-80W-RC`, but no warranties.

**Comment by sharkyenergy** [comment]
huhm, can I still restore the current situation in case it does not work or will I brick it? the current original firmware stops automatically with alarm at 5000 ma... so I cannot fully charge a battery in one go.. and there is no way to change this setting.. what about the dual charger? will it work even if mine has only one charging port?

**Comment by diggit** [comment]
You can also check pinout, [here is pin mapping used in cheali](https://github.com/stawel/cheali-charger/blob/master/src/hardware/atmega32/generic/50W/imaxB6-pins.h) and [here is schematic](http://www.rcgroups.com/forums/showatt.php?s=df7049bcbafdb5d7d06765c264e5c4bb&attachmentid=3693125&d=1293732709) (component references probably won't match).

Well, at first, you can try to make backup of [original FW](https://github.com/stawel/cheali-charger/blob/master/docs/flashing.md#flashing-using-avrdude). Once you have `hex` files, open `flash.hex` in plaintext editor and look if there is increasing sequence of hex numbers, if so, you MCU is protected against readout (highly probably). If not, you have obtained backup which can be flashed back any time.

All these chargers have one MCU per battery port, besides that, `dual-power` in that filename means, that charger could be powered from regular wall socket (AC) or some DC PSU. No effect on FW.

**Comment by sharkyenergy** [comment]
thank you very much!! will try this weekend! :)

**Comment by sharkyenergy** [comment]
It works like a charm! the code was not protected, so I still have a backup of the original one.. But this works wayyy better.. (although its slower in charging...) So i can confirm that the MonsterTronic MT680AC is compatible with the firmware cheali-charger-Dual-Power-B6AC-80W-RC

Thank you very much everybody

**Comment by diggit** [comment]
>  its slower in charging
how? lower max current/max power limits? That could be fixed...
