### ISSUE TITLE
Imax b6 new 1.8 version board

### ISSUE THREAD

**Issue by Vasud23** [stawel/cheali-charger#350]
Hi Pawel,

Can I get correct hex for the below board.

Notice that PCB on the upper right corner has an additional chip, 
1. Is an LM2904.
2. Pin 13 from 74HC4051 it doesn't connect to anything.
3. Pin 14 and 15 from 74HC4051 connected as the schema.

The charger is probably an improved version.

please check: https://groups.google.com/g/cheali-charger/c/1ez1qRu1Bgs

![IMG_9524](https://github.com/stawel/cheali-charger/assets/161311389/7ab8a7c7-4895-4be0-a86b-867149df320f)
![IMG_9523](https://github.com/stawel/cheali-charger/assets/161311389/b4421590-0f63-4e80-8bc6-733ccf074847)
![IMG_9525](https://github.com/stawel/cheali-charger/assets/161311389/805db734-1987-429a-869c-ad884285890b)

Thanks,
Vasu

**Comment by diggit** [comment]
Is your charger capable of 80W? If so, use cheali-charger-Dual-Power-B6AC-80W

**Comment by Vasud23** [comment]
I’m not sure, how we can check that?

**Comment by diggit** [comment]
It is usually written on the casing of the charger.

**Comment by Vasud23** [comment]
Yeah 80w, so I flash the charger with cheali-charger-Dual-Power-B6AC-80W. 

In expert Danger, there is no options for (Vb0pin, Vb1pin, Vb2pin). How I can calibrate my charger with this version?

**Comment by diggit** [comment]
There is no such option for 80 W variant, because there is no need for it. Only simplified circuitry in most 50 W chargers needs some additional calibration steps. 80 W chargers usually have differential amplifers on *all* balancer channels.

**Comment by Vasud23** [comment]
Ok, but I’m unable to set 2A for discharge, why?

**Comment by Vasud23** [comment]
Yeah ok got it, thanks man
