### ISSUE TITLE
Turnigy Accucel-6

### ISSUE THREAD

**Issue by tbaumann** [stawel/cheali-charger#5]
Is support for the Turnigy Accucel-6 also possible?
I might be a bit naive, but wasn't that also just a copy of the same basic design?
It was a clone of some common design, but it might have been a different family, I'm not sure now.

**Comment by biasedlogic** [comment]
"The lock fuse bits were open so I have backup of original firmware. Are you still looking for some measurements? I'm asking because this thread is open."

Would you mind sharing?

**Comment by przemekklosowski** [comment]
I noticed that sometimes accidental writes to the serial data port that's monitoring the charging hang the output. Is it possible that there are some commands that the original firmware accepts? did anyone see any evidence of the firmware reading data from the serial port?

**Comment by stawel** [comment]
in the atmega32 version only the TX pin is connected to the 
outgoing 3-pin plug:
pin 1 - GND
pin 2 - TX  (and temperature probe input)
pin 3 - 5V (through a resistor)

so, I don't thing the charger is accepting any incoming communication.

**Comment by biasedlogic** [comment]
But if TxD line from PC is connected to 5VCC it might possibly cause brownouts if a series of zeroes is sent down the line...

**Comment by stawel** [comment]
>outgoing 3-pin plug:
pin 1 - GND
pin 2 - TX (and temperature probe input)
pin 3 - 5V (through a resistor)

this is how the connector looks like from the chargers perspective,
if you are connecting a UART dongle to it you should only use:
"pin 1" and "pin 2"
