### ISSUE TITLE
logview: duplicated logs

### ISSUE THREAD

**Issue by stawel** [stawel/cheali-charger#71]
Kidiam:
$1;8;23433.4;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;2
$1;8;23433.5;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;3
$1;8;23433.5;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;3
$1;8;23433.5;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;3
$1;8;23433.6;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;0
$1;8;23433.6;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;0
$1;8;23433.7;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;1
$1;8;23433.7;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;1
$1;8;23433.8;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;14
$1;8;23433.8;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;14
$1;8;23433.9;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;15
$1;8;23433.9;2459;250;188;61;46;0;3468;14881;1202;1257;31;19;11;7;475;275;0;0;0;0;750;48;28;0;15
...

**Comment by stawel** [comment]
I'm couldn't reproduce this behavior (maybe I need to wait a little bit longer)
but I found another bug in the UART implementation, maybe they are related,
please try the new uploaded firmware.

**Comment by kidiam** [comment]
I got on new firmware (cheali-charger-imaxB6-clone_0.99-20150107_nuvoton-M0517.hex) same problem.
I missed one point: in a setting UART set to debug mode.
And found a new behavior:
$1;4;0.6;2744;0;0;0;0;0;3414;15205;1370;1374;33;20;12;8;0;0;0;0;0;0;0;0;46;0;57
$1;4;1.3;2744;0;0;0;0;0;3414;15205;1370;1374;33;20;12;8;0;0;0;0;0;0;0;0;46;0;61
$1;4;2.0;2744;0;0;0;0;0;3414;15205;1370;1374;33;20;12;8;0;0;0;0;0;0;0;0;46;0;61
$1;4;2.6;2744;0;0;0;0;0;3410;15205;1371;1373;33;20;12;8;0;0;0;0;0;0;0;0;46;0;57
$1;4;3.3;2744;0;0;0;0;0;3410;15205;1370;1374;33;20;12;8;0;0;0;0;0;0;0;0;46;0;59
$1;4;4.0;2744;0;0;0;0;0;3410;15205;1370;1374;33;20;12;8;0;0;0;0;0;0;0;0;46;0;63
...
$1;4;22410.0;2458;100;621;24;152;0;3345;15204;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;52
$1;4;22410.7;2458;100;621;24;152;0;3345;15204;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;51
$1;4;22411.4;2458;100;621;24;152;0;3345;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;54
$1;4;22412.0;2458;100;621;24;152;0;3345;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;49
$1;4;22412.8;2458;100;621;24;152;0;3349;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;53
$1;4;22413.4;2458;100;621;24;152;0;3345;15204;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;51
$1;4;22414.1;2458;100;621;24;152;0;3345;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;54
$1;4;22414.1;2458;100;621;24;152;0;3345;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;54
$1;4;22414.2;2458;100;621;24;152;0;3345;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;53
$1;4;22414.3;2458;100;621;24;152;0;3345;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;52
$1;4;22414.4;2458;100;621;24;152;0;3345;15203;1210;1248;31;19;11;7;460;300;0;0;0;0;760;30;28;0;51
...


1. Information not duplicated. Look like changed the time of delay between adjacent sending (6h13m).
![20150106_disch](https://cloud.githubusercontent.com/assets/10170412/5690459/fb6b3e58-9892-11e4-8f93-826599f7be85.gif)

2. It's strange but in the end of discharge the time of delay became to initial (~0.7s)
$1;4;44879.7;2390;100;1245;23;297;0;3387;15201;1170;1220;30;18;11;7;460;300;0;0;0;0;760;50;24;0;3
$1;4;44880.4;2390;100;1245;23;297;0;3384;15201;1170;1220;30;18;11;7;460;300;0;0;0;0;760;40;24;0;4
$1;4;44881.1;2390;100;1246;23;297;0;3387;15202;1170;1220;30;18;11;7;460;300;0;0;0;0;760;40;24;0;3
$1;4;44881.7;2390;100;1246;23;297;0;3387;15202;1170;1220;30;18;11;7;460;300;0;0;0;0;760;40;24;0;5

**Comment by stawel** [comment]
I'm trying to reproduce this error, so far without success.
I begin to suspect that this is just a LogView bug,
could you do me a favor?
please send me a dump made by hand (not LogView).
On linux:
$ cat /dev/ttyUSB0 > dump.txt
I'm not sure how to make it on windows, maybe something like this:
c:\> copy com1 dump.txt
or with some terminal program.

**Comment by stawel** [comment]
OK, I finely was able to reproduce the issue,
I don't need a dump anymore,

Best Regards,
Paweł
